# Generated by Django 6.0.1 on 2026-01-28 00:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='public_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
